### ISSUE TITLE
Second Game crashes without Legacy4J installed

### ISSUE THREAD

**Issue by agmass** [Jab125/hot-join#2]
- Run /hotjoin authme microsoft
- Log into microsoft
- First window's size and position gets changed accordingly
- Second window appears, gets suck at around 80% when loading and returns this in the console:

```
[21:28:07] [Render thread/ERROR]: Reported exception thrown!
net.minecraft.class_148: Rendering overlay
	at knot/net.minecraft.class_757.method_3192(class_757.java:909) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_310.method_1523(class_310.java:1285) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_310.method_1514(class_310.java:882) [client-intermediary.jar:?]
	at knot/net.minecraft.client.main.Main.main(Main.java:256) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480) [fabric-loader-0.16.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.16.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.16.7.jar:?]
Caused by: java.lang.NullPointerException: Cannot invoke "dev.jab125.hotjoin.compat.legacy4j.ILegacy4JModCompat.joinedWorld()" because "dev.jab125.hotjoin.HotJoin.legacy4JModCompat" is null
	at knot/dev.jab125.hotjoin.HotJoinClientInit.lambda$init$5(HotJoinClientInit.java:75) ~[hotjoin-0.3.0.jar:?]
	at knot/net.fabricmc.fabric.api.client.screen.v1.ScreenEvents.lambda$static$2(ScreenEvents.java:101) ~[fabric-screen-api-v1-2.0.25+8b68f1c719-9b98000b3dbb20ca.jar:?]
	at knot/net.minecraft.class_437.afterInit(class_437.java:1331) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_437.handler$znj000$fabric-screen-api-v1$afterInitScreen(class_437.java:1284) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_437.method_25423(class_437.java:318) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_425.method_25394(class_425.java:156) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_757.method_3192(class_757.java:902) ~[client-intermediary.jar:?]
	... 6 more
	```

**Comment by agmass** [comment]
after building development, it seems like this is already fixed. sorry!
